server:
  port: 8084  # Port du service PatientService

spring:
  application:
    name: prescription-service # Nom du service dans Eureka

  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/prescription_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: ${Eureka-Server-URL}  # URL du serveur Eureka
    fetch-registry: true  # Active la récupération des services enregistrés
    register-with-eureka: true  # Active l'enregistrement du service
  instance:
    hostname: localhost
    prefer-ip-address: true  # Utiliser l'adresse IP plutôt que le nom d'hôte
