server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patient/**

eureka:
  client:
    service-url:
      defaultZone: ${Eureka-Server-URL}